"""Assemble site/index.html from partials + section modules. Run: python site/_build/gen.py

Section module contract (site/sections/NN-name/):
  section.html  - ONE <section id="..." data-section="NN-name"> ... </section>, nothing else.
                  Write asset paths as {P}sections/NN-name/img/x.jpg - gen.py fills {P} per page depth.
  section.css   - every selector scoped under that section's id (or a unique .s-name class)
  section.js    - Select.register('NN-name', function (ctx) { ... })  (see assets/js/core.js)
  demo.html     - optional standalone QA page (generated by this script as sections/NN-name/demo.html)
Sections appear in folder-name order. index.html is GENERATED - never hand-edit it.
"""
import pathlib, re

SITE = pathlib.Path(__file__).resolve().parents[1]
SEC = SITE / "sections"
FONTS = ('<link rel="preconnect" href="https://fonts.googleapis.com">\n'
         '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
         '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:opsz,wght@6..96,400..700'
         '&family=Manrope:wght@400;500;600;700&display=swap">')
VENDOR = ''.join(f'<script src="{p}assets/vendor/{v}" defer></script>\n'
                 for p in ['{P}'] for v in ['gsap.min.js', 'ScrollTrigger.min.js', 'lenis.min.js'])


def read(p):
    return p.read_text(encoding="utf-8") if p.exists() else ""


def page(title, sections, prefix):
    css = ''.join(f'<link rel="stylesheet" href="{prefix}sections/{s.name}/section.css">\n'
                  for s in sections if (s / "section.css").exists())
    js = ''.join(f'<script src="{prefix}sections/{s.name}/section.js" defer></script>\n'
                 for s in sections if (s / "section.js").exists())
    # {P} in section.html = path prefix to site root ("" for index.html, "../../" for demo pages)
    body = '\n'.join(read(s / "section.html").replace('{P}', prefix) for s in sections)
    header = read(SITE / "partials" / "header.html").replace('{P}', prefix)
    foot = read(SITE / "partials" / "after.html").replace('{P}', prefix)
    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="robots" content="noindex">
{FONTS}
<link rel="stylesheet" href="{prefix}assets/css/tokens.css">
<link rel="stylesheet" href="{prefix}assets/css/chrome.css">
{css}{VENDOR.replace('{P}', prefix)}<script src="{prefix}assets/js/core.js" defer></script>
<script src="{prefix}assets/js/chrome.js" defer></script>
{js}</head>
<body>
<a class="skip" href="#main">Skip to content</a>
{header}
<main id="main">
{body}
</main>
{foot}
</body>
</html>
'''


def main():
    secs = sorted(p for p in SEC.iterdir() if p.is_dir() and re.match(r"\d\d-", p.name))
    (SITE / "index.html").write_text(page("duPont REGISTRY Select", secs, ""), encoding="utf-8")
    for s in secs:
        (s / "demo.html").write_text(page(f"{s.name} - demo", [s], "../../"), encoding="utf-8")
    print("built index.html with", [s.name for s in secs])
    fin = SEC / "08-showrooms" / "build_finance.py"
    if fin.exists():
        import runpy; runpy.run_path(str(fin), run_name="__main__"); print("built finance.html")


if __name__ == "__main__":
    main()
