"""Builds site/finance.html (designer, 08 owner). Run: python site/sections/08-showrooms/build_finance.py
Header = partials/header.html (in-page anchors pointed at index.html); footer = the practical sheet of
sections/08-showrooms/section.html. So the page never drifts from the homepage's header and footer.
(Orchestrator: this can move into _build/gen.py.)"""
import pathlib, re

SITE = pathlib.Path(__file__).resolve().parents[2]
FONTS = ('<link rel="preconnect" href="https://fonts.googleapis.com">\n'
         '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
         '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:opsz,wght@6..96,400..700'
         '&family=Manrope:wght@400;500;600;700&display=swap">')


def to_index(html):
    """in-page anchors (#x) of the homepage become index.html#x on this page"""
    return re.sub(r'href="#(?!main\b)([\w-]+)"', r'href="index.html#\1"', html)


header = (SITE / "partials/header.html").read_text(encoding="utf-8").replace("{P}", "")
header = to_index(header).replace('href="finance.html">Finance</a>', 'href="finance.html" aria-current="page">Finance</a>')
sec = (SITE / "sections/08-showrooms/section.html").read_text(encoding="utf-8").replace("{P}", "")
sheet = re.search(r'<footer class="sh__sheet".*?</footer>', sec, re.S).group(0)
sheet = to_index(sheet)

body = '''<main id="main" class="fin">
  <section class="fin__scene" aria-labelledby="fin-title">
    <div class="fin__slot">
      <p class="fin__eye">Finance <i aria-hidden="true">·</i> duPont REGISTRY Select</p>
      <h1 class="fin__head" id="fin-title">Finance.</h1>
      <p class="fin__lead">Ask how to finance a car from the Select inventory.</p>
      <p class="fin__tbc"><span>[Partner, rates and terms: awaiting client]</span></p>
      <p class="fin__acts">
        <a class="fin__btn fin__btn--red" href="index.html#contact">Ask about finance<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M2 8h11M9 4l4 4-4 4" fill="none" stroke="currentColor" stroke-width="1.4"/></svg></a>
        <a class="fin__btn" href="inventory.html">Browse the inventory<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M2 8h11M9 4l4 4-4 4" fill="none" stroke="currentColor" stroke-width="1.4"/></svg></a>
      </p>
    </div>
    <figure class="fin__fig">
      <div class="fin__win">
      <span class="fin__floor" aria-hidden="true"></span>
      <img class="fin__car" data-cut="616145-front34" src="assets/cutouts/616145-front34.webp" alt="A blue 2021 Ferrari 812 GTS, front three-quarter view" width="1715" height="616">
      </div>
      <figcaption class="fin__cap">Pictured <i aria-hidden="true">·</i> 2021 Ferrari 812 GTS <i aria-hidden="true">·</i> $770,075 <i aria-hidden="true">·</i> 4,433 mi <i aria-hidden="true">·</i> Southern California <i aria-hidden="true">·</i> as of 8&nbsp;Oct&nbsp;2026</figcaption>
    </figure>
  </section>
  <div class="s-showrooms sh--foot">
''' + sheet + '''
  </div>
</main>'''

page = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Finance — duPont REGISTRY Select</title>
<meta name="description" content="Finance for cars from the duPont REGISTRY Select inventory. Partner, rates and terms awaiting client.">
<meta name="robots" content="noindex">
<!-- GENERATED by sections/08-showrooms/build_finance.py - edit there. -->
{FONTS}
<link rel="stylesheet" href="assets/css/tokens.css">
<link rel="stylesheet" href="assets/css/chrome.css">
<link rel="stylesheet" href="sections/08-showrooms/section.css">
<link rel="stylesheet" href="assets/finance/finance.css">
<script src="assets/js/core.js" defer></script>
<script src="assets/js/chrome.js" defer></script>
</head>
<body class="fin-page">
<a class="skip" href="#main">Skip to content</a>
{header}
{body}
</body>
</html>
'''
(SITE / "finance.html").write_text(page, encoding="utf-8")
print("built finance.html")
